// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKhDnD30KsAEOfm3v_XX-cGvbCE8yuWDY',
    appId: '1:235961023298:web:0cd1dbc4d6cf8b08d566db',
    messagingSenderId: '235961023298',
    projectId: 'fahamni-dev',
    authDomain: 'fahamni-dev.firebaseapp.com',
    storageBucket: 'fahamni-dev.firebasestorage.app',
    measurementId: 'G-QP611EM7LY',
  );

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyAy-fb1VTMKL5ikeATWTxH5tTfiFX9uQN0',
  appId: '1:235961023298:android:cde146cf7839fed0d566db',
  messagingSenderId: '235961023298',
  projectId: 'fahamni-dev',
  storageBucket: 'fahamni-dev.firebasestorage.app',
);

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZrL2N5MMl3zTwbYC0P2KL4BqCyK22vrA',
    appId: '1:235961023298:ios:2d3a9c45280245d9d566db',
    messagingSenderId: '235961023298',
    projectId: 'fahamni-dev',
    storageBucket: 'fahamni-dev.firebasestorage.app',
    iosBundleId: 'com.example.fahamni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZrL2N5MMl3zTwbYC0P2KL4BqCyK22vrA',
    appId: '1:235961023298:ios:2d3a9c45280245d9d566db',
    messagingSenderId: '235961023298',
    projectId: 'fahamni-dev',
    storageBucket: 'fahamni-dev.firebasestorage.app',
    iosBundleId: 'com.example.fahamni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKhDnD30KsAEOfm3v_XX-cGvbCE8yuWDY',
    appId: '1:235961023298:web:5bd702b26a7b13d7d566db',
    messagingSenderId: '235961023298',
    projectId: 'fahamni-dev',
    authDomain: 'fahamni-dev.firebaseapp.com',
    storageBucket: 'fahamni-dev.firebasestorage.app',
    measurementId: 'G-B8RSRX965G',
  );
}
